add bug report template
stepci/stepci pull request #16
Opened 2022-10-07 19:52 UTC by dejmedus

Added bug_report.yml to .github/ISSUE_TEMPLATE

2022-10-08 09:12 UTC, mishushakov requested changes
Looks fantastic. The only suggestion I have is to change the version number from dropdown to input, so we don't have to maintain the list

2022-10-08 09:12 UTC, mishushakov commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +  - type: dropdown
Change this to input

2022-10-08 13:17 UTC, dejmedus commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +  - type: dropdown
Changed it

2022-10-08 13:32 UTC, mishushakov approved these changes

2022-10-08 13:32 UTC, merged

2022-10-08 13:32 UTC, mishushakov commented
Good enough, thanks!

2022-10-08 13:37 UTC, mishushakov commented
@dejmedus I also have these two issues that could use a little help:

- #7
- #8

You can subscribe to these issues and I'll continue there

2022-10-10 17:36 UTC, sebastianwis commented
Thank you very much, @dejmedus!
That helped a lot! 
Also, we are very happy to have you as our very first contributor to Step CI. 
It would be great if you would like to accompany us on the further journey in any way!