Add reference docs for CLI
stepci/stepci pull request #22
Opened 2022-10-12 21:16 UTC by Dinoosawruss

Issue: #8 

I have tried to reference all the current CLI and build a format in line with my preferences from parts of the [AWS CLI](https://docs.aws.amazon.com/cli/latest/reference), [Prisma CLI](https://www.prisma.io/docs/reference/api-reference/command-reference) and [Stripe CLI](https://stripe.com/docs/cli) reference guides. 

Hopefully, it covers everything and is in a style that is helpful and easy to follow

If you would like any changes made or if I have missed anything do let me know

2022-10-12 21:35 UTC, mishushakov requested changes
Fantastic work! Only small changes needed before we can merge. Thank you so much so far!

2022-10-12 21:35 UTC, mishushakov commented on docs/cli-reference.md
> +# StepCI CLI reference
Use "CLI Reference" instead of "StepCI CLI reference"

2022-10-12 21:35 UTC, mishushakov commented on docs/cli-reference.md
> +The following documents evety command and flag avaliable for use in StepCI's command-line interface.
Fix grammar: "evety" and "avaliable". Also Step CI is written with a space

2022-10-12 21:35 UTC, mishushakov commented on docs/cli-reference.md
> +
This is unnecessary and can be removed

2022-10-12 21:35 UTC, mishushakov commented on docs/cli-reference.md
> +Follow the [getting started guide](https://github.com/stepci/stepci/blob/main/docs/get-started.md) for setup instructions
Change the link to (../get-started.md). Also change setup instructions > installation instructions

2022-10-12 21:35 UTC, mishushakov commented on docs/cli-reference.md
> +The primary method to execute StepCI workflows is `stepci run [command]`
execute StepCI workflows > execute workflows

2022-10-12 21:35 UTC, mishushakov commented on docs/cli-reference.md
> +The `run ` command allows you to execute a specified workflow
allows you to execute > lets you execute

2022-10-12 21:35 UTC, mishushakov commented on docs/cli-reference.md
> +Run test workflow to return the status of [example.com](https://example.com)
Run test workflow to return the status > Run example workflow that checks the status

2022-10-12 21:35 UTC, mishushakov commented on docs/cli-reference.md
> +Outputs the help menu for the main `stepci` comamnd
Fix grammar: "comamnd"

2022-10-12 21:35 UTC, mishushakov commented on docs/cli-reference.md
> +Outputs the current version of stepci installed
Outputs the current version of stepci installed > Outputs the version currently installed

2022-10-12 21:35 UTC, mishushakov commented on docs/cli-reference.md
> +When `stepci` is called with the `--help` option a list of avaliable commands and options will be displayed:
add a comma after "option"

2022-10-12 21:35 UTC, mishushakov commented on docs/cli-reference.md
> +| workflow | Yes | Specify the path to a stepci workflow |
stepci workflow > workflow

2022-10-12 21:35 UTC, mishushakov commented on docs/cli-reference.md
> +| --version | No | Outputs the current stepci version |
current stepci version > current version

2022-10-12 21:36 UTC, mishushakov commented
Also don't forget to change `docs/README.md` to include `[CLI Reference](cli-reference.md)`

2022-10-12 21:52 UTC, Dinoosawruss commented
Should all be resolved

2022-10-12 21:53 UTC, mishushakov commented on docs/cli-reference.md
> +The `run ` command lets you execute a specified workflow
Remove space after run

2022-10-12 21:56 UTC, mishushakov commented on docs/README.md
> +- [CLI Reference](./cli-reference.md)
I think we need to reorder this bit

1. Get Started
2. CLI Reference
3. Workflow Syntax
4. Using in Test Tools

2022-10-12 22:01 UTC, mishushakov approved these changes
Amazing work. We're merging it!
Thank you Michael so much!

2022-10-12 22:01 UTC, merged

2022-10-13 10:50 UTC, mishushakov commented
By the way, I've adjusted your CLI reference a little bit: https://github.com/stepci/stepci/commit/dd0d1c2e6e4267efc4ddfb50536e5ca8e760ea6d

I learned that I shouldn't be too picky on pull requests, because making some small changes myself takes less time than actually communicating that these changes should to be made 🤷

2022-10-13 20:56 UTC, sebastianwis commented
Thank you so much, @Dinoosawruss !
We are happy to have you as contributor.
It would be amazing if you would like to accompany us on the further journey in any way!