feat : add default commands
stepci/stepci pull request #66
Opened 2022-11-10 16:02 UTC by LemonDouble

Hello! I Implement some default commands.

### it can shows

- show stepci version
- inform STEPCI_DISABLE_ANALYTICS variables
- show available commands.

and, it shows on my terminal like this.

![image](https://user-images.githubusercontent.com/31124212/201139902-199e7b18-e32a-4f84-9ed1-758290103a6b.png)

you can easily change default message in `src/lib/constants.ts` files.

### This is what changes.

*  I disable default yargs command `version`, and `help`.
    *  because the default command always shows help and versions. i think we don't need that commands.
* I set scriptname `""`
   * there is two reason.
   * first reason is yargs's `showHelp()` method show script name.
       *  so, if i set scriptName to "stepci", the default message show like this. (sadly, yargs can't disable that options)
       ![image](https://user-images.githubusercontent.com/31124212/201142007-bc21a83e-001e-4fd4-9c5f-904052a1bca7.png)
       * this looks confuse to me.
   * second reason is if we use yargs's `gethelp()` method, it is difficult to control order of  messages. because `gethelp()` method return promise.
   * if i use this code..
```typescript
...
  .command(['$0'], false, () => {}, async () => {
    console.log(stepCiDefaultText)
    await console.log(await getHelp())
    showHelp()
  })
  .help(false)
  .version(false)
  .parse()

sendAnalyticsEvent()
````
   * then the output look like this...
![image](https://user-images.githubusercontent.com/31124212/201142835-9ec994a8-68c7-4f9a-91f8-dd3567aa9046.png)

surely, i can handle it by moving `sendAnalyticsEvent()` function. but i think it make unintuitive code.
--

If there's anything I can do to help, I'll work on it more! thanks 😄

2022-11-16 13:54 UTC, mishushakov requested changes
Hello,
Sorry it took me so much time to respond

- We need the `version` and `help` commands, because this is how developers expect it to work
- Do not overwrite the `scriptname`
- On default command, do not show help - we only need to show a customised message

Would be happy to get back once you change the above. Other than that, looks fine 👍 
Thanks for your effort so far 🙏

2022-11-16 14:31 UTC, LemonDouble commented
@mishushakov 
i checked your review, and apply changes.

and.. I'd like to suggest one. how about add some document's link (https://docs.stepci.com/) on default commands?

it maybe looks like this. If you think it's ok, I'll add the commit. thanks! 
```
Weclome to StepCI! ( Version 2.4.5 )

StepCI use Anonymous data collection.
if you want to disable it, please set environment variable STEPCI_DISABLE_ANALYTICS=true.

if you want help, please visit our document page. ( https://docs.stepci.com )


ⓘ  Anonymous usage data collected. Learn more on https://step.ci/yUpOHmZ
```

2022-11-16 15:37 UTC, mishushakov commented
Looks good enough! I'll accept the PR and do some changes my self
Thank you very much 😍

2022-11-16 15:37 UTC, mishushakov approved these changes

2022-11-16 15:38 UTC, merged

2022-11-30 08:02 UTC, sebastianwis commented
Thank you so much for helping out, @LemonDouble! :)
Would be so nice to have you accompany us on the further journey in any way!